### ISSUE TITLE
Rookie Question - sorry!

### ISSUE THREAD

**Issue by jwar9** [WuYiming6526/HARD#1]
Hi! I'm not seeing the HARD-AUplugin.zip available anywhere for download - has it been taken down? If there's a direct link or any easy pathway to find and download it, I'd appreciate it so much. Thank you!!

**Comment by WuYiming6526** [comment]
Hi, it's indeed hard to find but it's placed at the Releases section. Here is the link: [HARD-AUplugin.zip](https://github.com/WuYiming6526/HARD/releases/download/v0.0.1/HARD-AUplugin.zip)
