### ISSUE TITLE
is this exclusive to MacOS?

### ISSUE THREAD

**Issue by 37735i6** [WuYiming6526/HARD#2]
hello thank you so much for sharing this amazing creation!! i discovered your plugin on twitter and i am absolutely adoring it, but i am wondering if this is currently limited to mac users only? i have downloaded the zip file and attempted to load it onto my daw by creating a file path in several VST plugin locations with no success. :( let me know if there is a way for windows users to still have this experience! thank you again!!!! :)

**Comment by WuYiming6526** [comment]
The plugin only runs on MacOS for now. The generative model could not perform real-time inference on Windows, even with newer CPUs like Core i7, so I did not build the Windows plugin. 

I will try to find a more efficient DNN architecture so that it can run on Windows as well.

**Comment by Kaszanas** [comment]
@WuYiming6526 Would it be possible to speed it up with a compatible GPU for model inference on Windows? Maybe then it could perform real-time?

**Comment by WuYiming6526** [comment]
I think so since the ONNX runtime seems to support inference with GPU. I'll see how to do this.
