### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by itsdvnk** [WuYiming6526/HARD#3]
Hi! First time github user here - I'm running 10.15.7 on my macbook pro and can't seem to get the component showing up in the plugin directories of any of my DAW's.

I've copied the HARD component onto both directories of the Library but still no luck. 

Any advice or recommendations on troubleshooting this?

**Comment by WuYiming6526** [comment]
Hi, I don't know which DAW you were using, but when I tested the plugin on Ableton Live, I had to enable AudioUnit plugins from the preferences page first. Can your DAW load the other AU plugins in your mac?

**Comment by itsdvnk** [comment]
I am using Ableton (11) as well. Have no issues with any of my other AU plugins, what plugin "manufacturer" is the plugin located in?

<img width="565" alt="Screen Shot 2023-04-11 at 7 44 12 PM" src="https://user-images.githubusercontent.com/130360352/231334626-299d8ad9-507f-492c-8830-3fdddc280be0.png">
<img width="637" alt="Screen Shot 2023-04-11 at 7 43 37 PM" src="https://user-images.githubusercontent.com/130360352/231334632-62826415-b1c0-4d91-8439-0f7fdb108290.png">
<img width="372" alt="Screen Shot 2023-04-11 at 7 42 38 PM" src="https://user-images.githubusercontent.com/130360352/231334636-89685b00-93e4-4a81-ba76-08262ab4a53f.png">
<img width="369" alt="Screen Shot 2023-04-11 at 7 42 21 PM" src="https://user-images.githubusercontent.com/130360352/231334637-8fd6c142-faae-42ff-a392-33d7e0d881ac.png">

**Comment by WuYiming6526** [comment]
It seems that you only copied the HARD binary file into the directory. You should copy the whole 'HARD.component' (whose size should be over 100 MB) to the directory, just like the other plugins.
The manufacturer is "AlphaTheta".

**Comment by itsdvnk** [comment]
I see, suspected that was the issue - however I don't see the .component file in the zip - I will try and download again and see if it pops up. Thank you!

update: All set! Thanks so much - seems like the .component got moved outside the download folder
