### ISSUE TITLE
"Plug-In could not be checked for malicious intent"

### ISSUE THREAD

**Issue by kemicreations** [WuYiming6526/HARD#4]
Hey there! I can't seem to find a way to enable the use of the HARD plug in. I tried system preferences-> security & privacy. I put the contents of the .zip into my plug-ins->components folder, but Logic just keeps telling me it is incompatible.

Any help would be greatly appreciated, and thank you so much for what you are doing!

**Comment by WuYiming6526** [comment]
Hi sorry for late reply. Did you find the notification on the "security & privacy" page that lets you allow running the HARD plugin specifically?

**Comment by kemicreations** [comment]
Hey my bad, I see it now! Easy to miss. thank you! can't wait to try it out
